// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Sep 25 19:09:08 2009

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

// mdda
#include <wx/wxprec.h>
#include <wx/cmdline.h>

#ifndef USBCONFIG_H
#define USBCONFIG_H

// begin wxGlade: ::extracode
// end wxGlade

class MyFrame: public wxFrame {
public:
  // begin wxGlade: MyFrame::ids
  // end wxGlade

  MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
  // begin wxGlade: MyFrame::methods
  void set_properties();
  void do_layout();
  // end wxGlade

protected:
  // begin wxGlade: MyFrame::attributes
  wxButton* button_1;
  // end wxGlade
}; // wxGlade: end class


// See : http://docs.wxwidgets.org/trunk/cmdline_8h.html
static const wxCmdLineEntryDesc g_cmdLineDesc [] = {
  { wxCMD_LINE_SWITCH, wxT("h"), wxT("help"), wxT("displays help on the command line parameters"),
       wxCMD_LINE_VAL_NONE, wxCMD_LINE_OPTION_HELP },
       
  { wxCMD_LINE_SWITCH, wxT("g"), wxT("gui"), wxT("enables the GUI (not yet)") },
  
  { wxCMD_LINE_SWITCH, wxT("q"), wxT("quiet"), wxT("don't show device settings") },  
  { wxCMD_LINE_SWITCH, wxT("d"), wxT("dump"), wxT("view current settings in parsable format") },  
  
  { wxCMD_LINE_OPTION, wxT("s"), wxT("slo"), wxT("set SLO scope state: 0=off, 1=2A, 2=1A.1D"), 
       wxCMD_LINE_VAL_NUMBER },
  { wxCMD_LINE_OPTION, wxT("p"), wxT("period"), wxT("set SLO scope period (new reading every (period+1)/12 microseconds, normal=539)"), 
       wxCMD_LINE_VAL_NUMBER },
       
  { wxCMD_LINE_OPTION, wxT("a"), wxT("line_a"), wxT("set line A state : { i|input, 0|low, 1|high }"), 
       wxCMD_LINE_VAL_STRING },
  { wxCMD_LINE_OPTION, wxT("b"), wxT("line_b"), wxT("set line B state : { i|input, 0|low, 1|high }"), 
       wxCMD_LINE_VAL_STRING },

  { wxCMD_LINE_SWITCH, wxT("t"), wxT("test"), wxT("do a test (defined by the code - usefull for developers)"), },
  
  { wxCMD_LINE_NONE }
};
 

#endif // USBCONFIG_H
